name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Installation des dépendances de développement
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Exécution des tests avec couverture
      run: |
        pytest tests/ --cov=src --cov-report=xml
    
    - name: Upload de la couverture de code
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 